
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vuejsdemo
    username: root
    password: admin

server:
  port: 80
logging:
  level:
    com.lss: debug
#    org.springframework: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.lss.pojo
#  mapper-locations: mapper/*.xml
